"""Backward-compatible public surface for the Leos agent runtime.

The runtime is split across focused modules. Importing from `leos_agent.core`
continues to work for existing callers.
"""

from __future__ import annotations

from .agent_loop import AgentLoop, AgentLoopConfig, AgentLoopResult, DeterministicProposalProvider, ProposalProvider
from .approval import (
    ApprovalDecision,
    ApprovalDecisionValue,
    ApprovalPacket,
    render_approval_packet_html,
    render_approval_packet_markdown,
)
from .approval_exchange import (
    FileApprovalGate,
    build_decision_for_packet,
    read_approval_decision,
    read_approval_packet,
    sign_approval_decision,
    verify_approval_decision_signature,
    write_approval_decision,
    write_approval_packet,
)
from .audit import AuditEvent, AuditLog
from .causal import (
    ActionConsequence,
    CausalEffect,
    CausalGraph,
    CausalHypothesis,
    CausalWorldModel,
    CounterfactualReport,
    CounterfactualReview,
    EffectPrediction,
)
from .causal_contract import CausalContract, safe_file_write_causal_contract
from .conflicts import Conflict, ConflictDetector, ConflictResolutionPolicy
from .credentials import (
    CredentialError,
    CredentialExpiredError,
    CredentialRevokedError,
    CredentialScopeError,
    CredentialVault,
    InMemoryCredentialVault,
    SecretHandle,
)
from .dev_tools import (
    GitDiffTool,
    ListFilesTool,
    PatchFileTool,
    ReadFileTool,
    RunTestsTool,
    default_dev_registry,
)
from .egress import EgressPolicy
from .enums import (
    CompensationStrategy,
    Decision,
    GoalStatus,
    Permission,
    Reversibility,
    RiskLevel,
    SandboxPolicy,
    StepStatus,
    TaskStatus,
)
from .errors import (
    BudgetExceeded,
    DryRunFailed,
    IdempotencyConflict,
    InvalidGoalTransition,
    LeosError,
    PolicyConfigurationError,
    PolicyDenied,
    PolicyIntegrityError,
    PostconditionFailed,
    PreconditionFailed,
    RollbackFailed,
    RuntimeEgressBlocked,
    SchemaValidationFailed,
    SecretBoundaryViolation,
    SecretLeakedToUntrustedTool,
    ToolTimeout,
    VerificationFailed,
    WorkspaceEscapeBlocked,
)
from .eval_runner import EvalReport, format_eval_report, render_eval_report_markdown, run_eval_suite, run_safety_evals
from .evaluator_registry import (
    CriterionEvaluation,
    CriterionRule,
    DomainEvaluator,
    EvaluatorRegistry,
)
from .github_agent import GitHubIssuePlanConfig, GitHubIssuePlanProvider
from .github_client import (
    GitHubAPIError,
    GitHubAuthError,
    GitHubConflictError,
    GitHubHTTPResponse,
    GitHubNotFoundError,
    GitHubRateLimitError,
    GitHubRESTClient,
    GitHubTransport,
    UrllibGitHubTransport,
)
from .github_tools import (
    GitHubCheckCIStatusTool,
    GitHubClient,
    GitHubCommentTool,
    GitHubCreateBranchTool,
    GitHubGetFileTool,
    GitHubOpenPRTool,
    GitHubReadIssueTool,
    GitHubUpdateFileTool,
    InMemoryGitHubClient,
)
from .goal_evaluator import GoalEvaluation, GoalEvaluationStatus, GoalEvaluator
from .goals import Goal, GoalCriterion, ResourceBudget
from .kernel import AgentKernel
from .manifest import (
    ToolManifest,
    load_tool_manifest_file,
    tool_manifest_from_mapping,
    validate_json_schema,
    validate_tool_manifest,
)
from .memory import MemoryRecord, MemorySensitivity, MemoryStore, MemoryType
from .model import (  # noqa: F401
    FakeModelClient,
    ModelCallError,
    ModelClient,
    ModelRequest,
    ModelResponse,
    ModelUsage,
    StructuredOutputError,
)
from .model_adapters import AnthropicModelClient, LocalHTTPModelClient, OpenAIModelClient
from .network_guard import RuntimeEgressDecision, RuntimeEgressGuard
from .network_tools import (
    BrowserReadTool,
    DNSResolver,
    NetworkFetcher,
    NetworkFetchResponse,
    NetworkFetchTool,
    URLSafetyPolicy,
    make_untrusted_observation,
)
from .planner import (  # noqa: F401
    LLMPlannerAdapter,
    Planner,
    StructuredLLMPlanner,
    validate_llm_proposals,
)
from .plans import (
    ActionStep,
    PlanCandidate,
    PlannerConfig,
    PlannerResult,
    PlanProposal,
    PlanScore,
    StateCondition,
    TransactionPlan,
)
from .policy import (
    BUILT_IN_POLICY_PROFILES,
    ApprovalGate,
    ApprovalRequest,
    CapabilityGrant,
    InteractiveApprovalGate,
    PolicyEngine,
    PolicyProfile,
    PolicyRule,
    build_approval_request,
    validate_policy_config,
)
from .policy_manifest import (
    SignedPolicyManifest,
    load_policy_from_file,
    manifest_to_json,
    sign_policy,
    verify_policy_manifest,
)
from .prompts import (  # noqa: F401
    DEFAULT_PROMPT_REGISTRY,
    PromptRegistry,
    PromptTemplate,
)
from .proof import ProofManifest, exit_code_for_manifest, generate_proofs
from .recovery import ManualRecoveryPacket
from .replanning import FailureAnalysis, FailureAnalyzer, FailureType, PlanRepairStrategy, ReplanContext
from .replay import AuditReplayer, ReplayResult, replay_audit_log
from .runtime_store import InMemoryRuntimeStore, JsonlRuntimeStore, RuntimeStore, RuntimeStoreError
from .sandbox import (  # noqa: F401
    ContainerSandboxRunner,
    DockerSandboxRunner,
    MicroVMSandboxRunner,
    SandboxCommand,
    SandboxCommandTool,
    SandboxResult,
    SandboxRunner,
    SandboxUnavailable,
    WorkspaceSubprocessSandboxRunner,
)
from .sanitization import (
    SanitizationError,
    SanitizationMode,
    assert_no_secrets,
    redact_secrets,
    safe_json_dumps,
    sanitize_for_boundary,
)
from .simulation import (
    FakeBrowser,
    FakeCalendar,
    FakeEmailServer,
    FakeFileSystem,
    FakeGitHubRepo,
    FakePaymentSystem,
    FakeShell,
    SimulationEnvironment,
)
from .sqlite_store import SQLiteRuntimeStore
from .state import TrustLevel, WorldState
from .task_queue import (
    RetryPolicy,
    RuntimeTask,
    TaskQueue,
    TaskRunner,
    TimeoutPolicy,
    Watchdog,
)
from .tool_manifest_registry import ToolManifestRegistry, ToolManifestRegistryError
from .tools import (
    EchoTool,
    RuntimeAttestedTool,
    SafeFileWriteTool,
    Secret,
    Tool,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    default_registry,
)
from .trace_viewer import render_trace_html, render_trace_markdown
from .transactions import TransactionManager

__all__ = [
    "ActionConsequence",
    "ActionStep",
    "AgentLoop",
    "AgentLoopConfig",
    "AgentLoopResult",
    "AgentKernel",
    "AnthropicModelClient",
    "ApprovalDecision",
    "ApprovalDecisionValue",
    "ApprovalGate",
    "ApprovalPacket",
    "ApprovalRequest",
    "AuditEvent",
    "AuditLog",
    "AuditReplayer",
    "BUILT_IN_POLICY_PROFILES",
    "BrowserReadTool",
    "BudgetExceeded",
    "CapabilityGrant",
    "CausalContract",
    "CausalEffect",
    "CausalGraph",
    "CausalHypothesis",
    "CausalWorldModel",
    "CompensationStrategy",
    "Conflict",
    "ConflictDetector",
    "ConflictResolutionPolicy",
    "CounterfactualReport",
    "CounterfactualReview",
    "CredentialError",
    "CredentialExpiredError",
    "CredentialRevokedError",
    "CredentialScopeError",
    "CredentialVault",
    "CriterionEvaluation",
    "CriterionRule",
    "Decision",
    "DryRunFailed",
    "DockerSandboxRunner",
    "DomainEvaluator",
    "DeterministicProposalProvider",
    "DNSResolver",
    "EchoTool",
    "EffectPrediction",
    "EvalReport",
    "EvaluatorRegistry",
    "EgressPolicy",
    "FakeBrowser",
    "FakeCalendar",
    "FakeEmailServer",
    "FakeFileSystem",
    "FakeGitHubRepo",
    "FakePaymentSystem",
    "FakeShell",
    "FileApprovalGate",
    "GitDiffTool",
    "GitHubAPIError",
    "GitHubAuthError",
    "GitHubCheckCIStatusTool",
    "GitHubClient",
    "GitHubCommentTool",
    "GitHubConflictError",
    "GitHubCreateBranchTool",
    "GitHubGetFileTool",
    "GitHubHTTPResponse",
    "GitHubIssuePlanConfig",
    "GitHubIssuePlanProvider",
    "GitHubNotFoundError",
    "GitHubOpenPRTool",
    "GitHubRESTClient",
    "GitHubRateLimitError",
    "GitHubReadIssueTool",
    "GitHubTransport",
    "GitHubUpdateFileTool",
    "Goal",
    "GoalCriterion",
    "GoalEvaluation",
    "GoalEvaluationStatus",
    "GoalEvaluator",
    "GoalStatus",
    "IdempotencyConflict",
    "FailureAnalysis",
    "FailureAnalyzer",
    "FailureType",
    "InMemoryGitHubClient",
    "InMemoryCredentialVault",
    "InMemoryRuntimeStore",
    "InteractiveApprovalGate",
    "InvalidGoalTransition",
    "JsonlRuntimeStore",
    "SQLiteRuntimeStore",
    "LeosError",
    "ListFilesTool",
    "LocalHTTPModelClient",
    "ManualRecoveryPacket",
    "MemoryRecord",
    "MemorySensitivity",
    "MemoryStore",
    "MemoryType",
    "ModelClient",
    "ModelRequest",
    "ModelResponse",
    "ModelUsage",
    "NetworkFetcher",
    "NetworkFetchResponse",
    "NetworkFetchTool",
    "OpenAIModelClient",
    "PatchFileTool",
    "Permission",
    "PlanCandidate",
    "PlanRepairStrategy",
    "PlanProposal",
    "PlanScore",
    "Planner",
    "PlannerConfig",
    "PlannerResult",
    "PolicyConfigurationError",
    "PolicyDenied",
    "PolicyEngine",
    "PolicyIntegrityError",
    "PolicyProfile",
    "PolicyRule",
    "ProposalProvider",
    "ProofManifest",
    "PostconditionFailed",
    "PreconditionFailed",
    "Reversibility",
    "RiskLevel",
    "ReplayResult",
    "ResourceBudget",
    "ReplanContext",
    "ReadFileTool",
    "RetryPolicy",
    "RollbackFailed",
    "RuntimeAttestedTool",
    "RuntimeEgressBlocked",
    "RuntimeEgressDecision",
    "RuntimeEgressGuard",
    "RuntimeTask",
    "RuntimeStore",
    "RuntimeStoreError",
    "RunTestsTool",
    "SafeFileWriteTool",
    "SandboxCommand",
    "SandboxCommandTool",
    "SandboxPolicy",
    "SanitizationError",
    "SanitizationMode",
    "SchemaValidationFailed",
    "Secret",
    "SecretHandle",
    "SecretBoundaryViolation",
    "SecretLeakedToUntrustedTool",
    "SimulationEnvironment",
    "SignedPolicyManifest",
    "StateCondition",
    "StepStatus",
    "StructuredLLMPlanner",
    "TaskQueue",
    "TaskRunner",
    "TaskStatus",
    "Tool",
    "ToolManifest",
    "ToolManifestRegistry",
    "ToolManifestRegistryError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolTimeout",
    "SandboxResult",
    "SandboxRunner",
    "SandboxUnavailable",
    "URLSafetyPolicy",
    "UrllibGitHubTransport",
    "TransactionManager",
    "TransactionPlan",
    "TrustLevel",
    "TimeoutPolicy",
    "VerificationFailed",
    "WorkspaceEscapeBlocked",
    "WorldState",
    "Watchdog",
    "assert_no_secrets",
    "build_decision_for_packet",
    "default_dev_registry",
    "default_registry",
    "build_approval_request",
    "exit_code_for_manifest",
    "format_eval_report",
    "generate_proofs",
    "load_policy_from_file",
    "load_tool_manifest_file",
    "manifest_to_json",
    "make_untrusted_observation",
    "read_approval_decision",
    "read_approval_packet",
    "replay_audit_log",
    "render_eval_report_markdown",
    "render_approval_packet_html",
    "render_approval_packet_markdown",
    "render_trace_html",
    "render_trace_markdown",
    "run_safety_evals",
    "run_eval_suite",
    "redact_secrets",
    "safe_json_dumps",
    "safe_file_write_causal_contract",
    "sanitize_for_boundary",
    "sign_approval_decision",
    "sign_policy",
    "validate_policy_config",
    "validate_json_schema",
    "tool_manifest_from_mapping",
    "validate_tool_manifest",
    "verify_policy_manifest",
    "verify_approval_decision_signature",
    "write_approval_decision",
    "write_approval_packet",
]

__all__ = sorted(set(__all__))
